/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module ripple_carry_synth(a, b, cin, sum, cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  wire \ripple_adders[0].fa.sum ;
  wire \ripple_adders[10].fa.sum ;
  wire \ripple_adders[11].fa.sum ;
  wire \ripple_adders[12].fa.sum ;
  wire \ripple_adders[13].fa.sum ;
  wire \ripple_adders[14].fa.sum ;
  wire \ripple_adders[15].fa.sum ;
  wire \ripple_adders[16].fa.sum ;
  wire \ripple_adders[17].fa.sum ;
  wire \ripple_adders[18].fa.sum ;
  wire \ripple_adders[19].fa.sum ;
  wire \ripple_adders[1].fa.sum ;
  wire \ripple_adders[20].fa.sum ;
  wire \ripple_adders[21].fa.sum ;
  wire \ripple_adders[22].fa.sum ;
  wire \ripple_adders[23].fa.sum ;
  wire \ripple_adders[24].fa.sum ;
  wire \ripple_adders[25].fa.sum ;
  wire \ripple_adders[26].fa.sum ;
  wire \ripple_adders[27].fa.sum ;
  wire \ripple_adders[28].fa.sum ;
  wire \ripple_adders[29].fa.sum ;
  wire \ripple_adders[2].fa.sum ;
  wire \ripple_adders[30].fa.sum ;
  wire \ripple_adders[31].fa.sum ;
  wire \ripple_adders[3].fa.sum ;
  wire \ripple_adders[4].fa.sum ;
  wire \ripple_adders[5].fa.sum ;
  wire \ripple_adders[6].fa.sum ;
  wire \ripple_adders[7].fa.sum ;
  wire \ripple_adders[8].fa.sum ;
  wire \ripple_adders[9].fa.sum ;
  output [31:0] sum;
  wire [31:0] sum;
  sky130_fd_sc_hd__or2_2 _127_ (
    .A(b[0]),
    .B(a[0]),
    .X(_126_)
  );
  sky130_fd_sc_hd__nand2_2 _128_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_2 _129_ (
    .A(_126_),
    .B(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xnor2_2 _130_ (
    .A(cin),
    .B(_001_),
    .Y(\ripple_adders[0].fa.sum )
  );
  sky130_fd_sc_hd__a21bo_2 _131_ (
    .A1(cin),
    .A2(_126_),
    .B1_N(_000_),
    .X(_002_)
  );
  sky130_fd_sc_hd__or2_2 _132_ (
    .A(b[1]),
    .B(a[1]),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2_2 _133_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_2 _134_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor2_2 _135_ (
    .A(_002_),
    .B(_005_),
    .Y(\ripple_adders[1].fa.sum )
  );
  sky130_fd_sc_hd__a21bo_2 _136_ (
    .A1(_002_),
    .A2(_003_),
    .B1_N(_004_),
    .X(_006_)
  );
  sky130_fd_sc_hd__or2_2 _137_ (
    .A(b[2]),
    .B(a[2]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand2_2 _138_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_2 _139_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor2_2 _140_ (
    .A(_006_),
    .B(_009_),
    .Y(\ripple_adders[2].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _141_ (
    .A(b[3]),
    .B(a[3]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_2 _142_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_2 _143_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a21bo_2 _144_ (
    .A1(_006_),
    .A2(_007_),
    .B1_N(_008_),
    .X(_013_)
  );
  sky130_fd_sc_hd__xnor2_2 _145_ (
    .A(_012_),
    .B(_013_),
    .Y(\ripple_adders[3].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _146_ (
    .A(b[4]),
    .B(a[4]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_2 _147_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_2 _148_ (
    .A(_014_),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21bo_2 _149_ (
    .A1(_010_),
    .A2(_013_),
    .B1_N(_011_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_2 _150_ (
    .A(_016_),
    .B(_017_),
    .Y(\ripple_adders[4].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _151_ (
    .A(b[5]),
    .B(a[5]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_2 _152_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_2 _153_ (
    .A(_018_),
    .B(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21bo_2 _154_ (
    .A1(_014_),
    .A2(_017_),
    .B1_N(_015_),
    .X(_021_)
  );
  sky130_fd_sc_hd__xnor2_2 _155_ (
    .A(_020_),
    .B(_021_),
    .Y(\ripple_adders[5].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _156_ (
    .A(b[6]),
    .B(a[6]),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand2_2 _157_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_2 _158_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21bo_2 _159_ (
    .A1(_018_),
    .A2(_021_),
    .B1_N(_019_),
    .X(_025_)
  );
  sky130_fd_sc_hd__xnor2_2 _160_ (
    .A(_024_),
    .B(_025_),
    .Y(\ripple_adders[6].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _161_ (
    .A(b[7]),
    .B(a[7]),
    .X(_026_)
  );
  sky130_fd_sc_hd__nand2_2 _162_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_2 _163_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a21bo_2 _164_ (
    .A1(_022_),
    .A2(_025_),
    .B1_N(_023_),
    .X(_029_)
  );
  sky130_fd_sc_hd__xnor2_2 _165_ (
    .A(_028_),
    .B(_029_),
    .Y(\ripple_adders[7].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _166_ (
    .A(b[8]),
    .B(a[8]),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand2_2 _167_ (
    .A(b[8]),
    .B(a[8]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_2 _168_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21bo_2 _169_ (
    .A1(_026_),
    .A2(_029_),
    .B1_N(_027_),
    .X(_033_)
  );
  sky130_fd_sc_hd__xnor2_2 _170_ (
    .A(_032_),
    .B(_033_),
    .Y(\ripple_adders[8].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _171_ (
    .A(b[9]),
    .B(a[9]),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2_2 _172_ (
    .A(b[9]),
    .B(a[9]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_2 _173_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21bo_2 _174_ (
    .A1(_030_),
    .A2(_033_),
    .B1_N(_031_),
    .X(_037_)
  );
  sky130_fd_sc_hd__xnor2_2 _175_ (
    .A(_036_),
    .B(_037_),
    .Y(\ripple_adders[9].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _176_ (
    .A(b[10]),
    .B(a[10]),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand2_2 _177_ (
    .A(b[10]),
    .B(a[10]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_2 _178_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21bo_2 _179_ (
    .A1(_034_),
    .A2(_037_),
    .B1_N(_035_),
    .X(_041_)
  );
  sky130_fd_sc_hd__xnor2_2 _180_ (
    .A(_040_),
    .B(_041_),
    .Y(\ripple_adders[10].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _181_ (
    .A(b[11]),
    .B(a[11]),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand2_2 _182_ (
    .A(b[11]),
    .B(a[11]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _183_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a21bo_2 _184_ (
    .A1(_038_),
    .A2(_041_),
    .B1_N(_039_),
    .X(_045_)
  );
  sky130_fd_sc_hd__xnor2_2 _185_ (
    .A(_044_),
    .B(_045_),
    .Y(\ripple_adders[11].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _186_ (
    .A(b[12]),
    .B(a[12]),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2_2 _187_ (
    .A(b[12]),
    .B(a[12]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_2 _188_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21bo_2 _189_ (
    .A1(_042_),
    .A2(_045_),
    .B1_N(_043_),
    .X(_049_)
  );
  sky130_fd_sc_hd__xnor2_2 _190_ (
    .A(_048_),
    .B(_049_),
    .Y(\ripple_adders[12].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _191_ (
    .A(b[13]),
    .B(a[13]),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand2_2 _192_ (
    .A(b[13]),
    .B(a[13]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_2 _193_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a21bo_2 _194_ (
    .A1(_046_),
    .A2(_049_),
    .B1_N(_047_),
    .X(_053_)
  );
  sky130_fd_sc_hd__xnor2_2 _195_ (
    .A(_052_),
    .B(_053_),
    .Y(\ripple_adders[13].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _196_ (
    .A(b[14]),
    .B(a[14]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand2_2 _197_ (
    .A(b[14]),
    .B(a[14]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_2 _198_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a21bo_2 _199_ (
    .A1(_050_),
    .A2(_053_),
    .B1_N(_051_),
    .X(_057_)
  );
  sky130_fd_sc_hd__xnor2_2 _200_ (
    .A(_056_),
    .B(_057_),
    .Y(\ripple_adders[14].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _201_ (
    .A(b[15]),
    .B(a[15]),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand2_2 _202_ (
    .A(b[15]),
    .B(a[15]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_2 _203_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21bo_2 _204_ (
    .A1(_054_),
    .A2(_057_),
    .B1_N(_055_),
    .X(_061_)
  );
  sky130_fd_sc_hd__xnor2_2 _205_ (
    .A(_060_),
    .B(_061_),
    .Y(\ripple_adders[15].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _206_ (
    .A(b[16]),
    .B(a[16]),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_2 _207_ (
    .A(b[16]),
    .B(a[16]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_2 _208_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a21bo_2 _209_ (
    .A1(_058_),
    .A2(_061_),
    .B1_N(_059_),
    .X(_065_)
  );
  sky130_fd_sc_hd__xnor2_2 _210_ (
    .A(_064_),
    .B(_065_),
    .Y(\ripple_adders[16].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _211_ (
    .A(b[17]),
    .B(a[17]),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand2_2 _212_ (
    .A(b[17]),
    .B(a[17]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_2 _213_ (
    .A(_066_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a21bo_2 _214_ (
    .A1(_062_),
    .A2(_065_),
    .B1_N(_063_),
    .X(_069_)
  );
  sky130_fd_sc_hd__xnor2_2 _215_ (
    .A(_068_),
    .B(_069_),
    .Y(\ripple_adders[17].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _216_ (
    .A(b[18]),
    .B(a[18]),
    .X(_070_)
  );
  sky130_fd_sc_hd__nand2_2 _217_ (
    .A(b[18]),
    .B(a[18]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_2 _218_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a21bo_2 _219_ (
    .A1(_066_),
    .A2(_069_),
    .B1_N(_067_),
    .X(_073_)
  );
  sky130_fd_sc_hd__xnor2_2 _220_ (
    .A(_072_),
    .B(_073_),
    .Y(\ripple_adders[18].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _221_ (
    .A(b[19]),
    .B(a[19]),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand2_2 _222_ (
    .A(b[19]),
    .B(a[19]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_2 _223_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a21bo_2 _224_ (
    .A1(_070_),
    .A2(_073_),
    .B1_N(_071_),
    .X(_077_)
  );
  sky130_fd_sc_hd__xnor2_2 _225_ (
    .A(_076_),
    .B(_077_),
    .Y(\ripple_adders[19].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _226_ (
    .A(b[20]),
    .B(a[20]),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2_2 _227_ (
    .A(b[20]),
    .B(a[20]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_2 _228_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a21bo_2 _229_ (
    .A1(_074_),
    .A2(_077_),
    .B1_N(_075_),
    .X(_081_)
  );
  sky130_fd_sc_hd__xnor2_2 _230_ (
    .A(_080_),
    .B(_081_),
    .Y(\ripple_adders[20].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _231_ (
    .A(b[21]),
    .B(a[21]),
    .X(_082_)
  );
  sky130_fd_sc_hd__nand2_2 _232_ (
    .A(b[21]),
    .B(a[21]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_2 _233_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a21bo_2 _234_ (
    .A1(_078_),
    .A2(_081_),
    .B1_N(_079_),
    .X(_085_)
  );
  sky130_fd_sc_hd__xnor2_2 _235_ (
    .A(_084_),
    .B(_085_),
    .Y(\ripple_adders[21].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _236_ (
    .A(b[22]),
    .B(a[22]),
    .X(_086_)
  );
  sky130_fd_sc_hd__nand2_2 _237_ (
    .A(b[22]),
    .B(a[22]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_2 _238_ (
    .A(_086_),
    .B(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a21bo_2 _239_ (
    .A1(_082_),
    .A2(_085_),
    .B1_N(_083_),
    .X(_089_)
  );
  sky130_fd_sc_hd__xnor2_2 _240_ (
    .A(_088_),
    .B(_089_),
    .Y(\ripple_adders[22].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _241_ (
    .A(b[23]),
    .B(a[23]),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand2_2 _242_ (
    .A(b[23]),
    .B(a[23]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_2 _243_ (
    .A(_090_),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21bo_2 _244_ (
    .A1(_086_),
    .A2(_089_),
    .B1_N(_087_),
    .X(_093_)
  );
  sky130_fd_sc_hd__xnor2_2 _245_ (
    .A(_092_),
    .B(_093_),
    .Y(\ripple_adders[23].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _246_ (
    .A(b[24]),
    .B(a[24]),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand2_2 _247_ (
    .A(b[24]),
    .B(a[24]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_2 _248_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21bo_2 _249_ (
    .A1(_090_),
    .A2(_093_),
    .B1_N(_091_),
    .X(_097_)
  );
  sky130_fd_sc_hd__xnor2_2 _250_ (
    .A(_096_),
    .B(_097_),
    .Y(\ripple_adders[24].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _251_ (
    .A(b[25]),
    .B(a[25]),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand2_2 _252_ (
    .A(b[25]),
    .B(a[25]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_2 _253_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21bo_2 _254_ (
    .A1(_094_),
    .A2(_097_),
    .B1_N(_095_),
    .X(_101_)
  );
  sky130_fd_sc_hd__xnor2_2 _255_ (
    .A(_100_),
    .B(_101_),
    .Y(\ripple_adders[25].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _256_ (
    .A(b[26]),
    .B(a[26]),
    .X(_102_)
  );
  sky130_fd_sc_hd__nand2_2 _257_ (
    .A(b[26]),
    .B(a[26]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_2 _258_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21bo_2 _259_ (
    .A1(_098_),
    .A2(_101_),
    .B1_N(_099_),
    .X(_105_)
  );
  sky130_fd_sc_hd__xnor2_2 _260_ (
    .A(_104_),
    .B(_105_),
    .Y(\ripple_adders[26].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _261_ (
    .A(b[27]),
    .B(a[27]),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand2_2 _262_ (
    .A(b[27]),
    .B(a[27]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_2 _263_ (
    .A(_106_),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21bo_2 _264_ (
    .A1(_102_),
    .A2(_105_),
    .B1_N(_103_),
    .X(_109_)
  );
  sky130_fd_sc_hd__xnor2_2 _265_ (
    .A(_108_),
    .B(_109_),
    .Y(\ripple_adders[27].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _266_ (
    .A(b[28]),
    .B(a[28]),
    .X(_110_)
  );
  sky130_fd_sc_hd__nand2_2 _267_ (
    .A(b[28]),
    .B(a[28]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand2_2 _268_ (
    .A(_110_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21bo_2 _269_ (
    .A1(_106_),
    .A2(_109_),
    .B1_N(_107_),
    .X(_113_)
  );
  sky130_fd_sc_hd__xnor2_2 _270_ (
    .A(_112_),
    .B(_113_),
    .Y(\ripple_adders[28].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _271_ (
    .A(b[29]),
    .B(a[29]),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand2_2 _272_ (
    .A(b[29]),
    .B(a[29]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_2 _273_ (
    .A(_114_),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21bo_2 _274_ (
    .A1(_110_),
    .A2(_113_),
    .B1_N(_111_),
    .X(_117_)
  );
  sky130_fd_sc_hd__xnor2_2 _275_ (
    .A(_116_),
    .B(_117_),
    .Y(\ripple_adders[29].fa.sum )
  );
  sky130_fd_sc_hd__or2_2 _276_ (
    .A(b[30]),
    .B(a[30]),
    .X(_118_)
  );
  sky130_fd_sc_hd__nand2_2 _277_ (
    .A(b[30]),
    .B(a[30]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_2 _278_ (
    .A(_118_),
    .B(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21bo_2 _279_ (
    .A1(_114_),
    .A2(_117_),
    .B1_N(_115_),
    .X(_121_)
  );
  sky130_fd_sc_hd__xnor2_2 _280_ (
    .A(_120_),
    .B(_121_),
    .Y(\ripple_adders[30].fa.sum )
  );
  sky130_fd_sc_hd__and2_2 _281_ (
    .A(b[31]),
    .B(a[31]),
    .X(_122_)
  );
  sky130_fd_sc_hd__a21boi_2 _282_ (
    .A1(_118_),
    .A2(_121_),
    .B1_N(_119_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_2 _283_ (
    .A(b[31]),
    .B(a[31]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_2 _284_ (
    .A(_122_),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21bai_2 _285_ (
    .A1(_123_),
    .A2(_124_),
    .B1_N(_122_),
    .Y(cout)
  );
  sky130_fd_sc_hd__xnor2_2 _286_ (
    .A(_123_),
    .B(_125_),
    .Y(\ripple_adders[31].fa.sum )
  );
  sky130_fd_sc_hd__buf_2 _287_ (
    .A(\ripple_adders[0].fa.sum ),
    .X(sum[0])
  );
  sky130_fd_sc_hd__buf_2 _288_ (
    .A(\ripple_adders[1].fa.sum ),
    .X(sum[1])
  );
  sky130_fd_sc_hd__buf_2 _289_ (
    .A(\ripple_adders[2].fa.sum ),
    .X(sum[2])
  );
  sky130_fd_sc_hd__buf_2 _290_ (
    .A(\ripple_adders[3].fa.sum ),
    .X(sum[3])
  );
  sky130_fd_sc_hd__buf_2 _291_ (
    .A(\ripple_adders[4].fa.sum ),
    .X(sum[4])
  );
  sky130_fd_sc_hd__buf_2 _292_ (
    .A(\ripple_adders[5].fa.sum ),
    .X(sum[5])
  );
  sky130_fd_sc_hd__buf_2 _293_ (
    .A(\ripple_adders[6].fa.sum ),
    .X(sum[6])
  );
  sky130_fd_sc_hd__buf_2 _294_ (
    .A(\ripple_adders[7].fa.sum ),
    .X(sum[7])
  );
  sky130_fd_sc_hd__buf_2 _295_ (
    .A(\ripple_adders[8].fa.sum ),
    .X(sum[8])
  );
  sky130_fd_sc_hd__buf_2 _296_ (
    .A(\ripple_adders[9].fa.sum ),
    .X(sum[9])
  );
  sky130_fd_sc_hd__buf_2 _297_ (
    .A(\ripple_adders[10].fa.sum ),
    .X(sum[10])
  );
  sky130_fd_sc_hd__buf_2 _298_ (
    .A(\ripple_adders[11].fa.sum ),
    .X(sum[11])
  );
  sky130_fd_sc_hd__buf_2 _299_ (
    .A(\ripple_adders[12].fa.sum ),
    .X(sum[12])
  );
  sky130_fd_sc_hd__buf_2 _300_ (
    .A(\ripple_adders[13].fa.sum ),
    .X(sum[13])
  );
  sky130_fd_sc_hd__buf_2 _301_ (
    .A(\ripple_adders[14].fa.sum ),
    .X(sum[14])
  );
  sky130_fd_sc_hd__buf_2 _302_ (
    .A(\ripple_adders[15].fa.sum ),
    .X(sum[15])
  );
  sky130_fd_sc_hd__buf_2 _303_ (
    .A(\ripple_adders[16].fa.sum ),
    .X(sum[16])
  );
  sky130_fd_sc_hd__buf_2 _304_ (
    .A(\ripple_adders[17].fa.sum ),
    .X(sum[17])
  );
  sky130_fd_sc_hd__buf_2 _305_ (
    .A(\ripple_adders[18].fa.sum ),
    .X(sum[18])
  );
  sky130_fd_sc_hd__buf_2 _306_ (
    .A(\ripple_adders[19].fa.sum ),
    .X(sum[19])
  );
  sky130_fd_sc_hd__buf_2 _307_ (
    .A(\ripple_adders[20].fa.sum ),
    .X(sum[20])
  );
  sky130_fd_sc_hd__buf_2 _308_ (
    .A(\ripple_adders[21].fa.sum ),
    .X(sum[21])
  );
  sky130_fd_sc_hd__buf_2 _309_ (
    .A(\ripple_adders[22].fa.sum ),
    .X(sum[22])
  );
  sky130_fd_sc_hd__buf_2 _310_ (
    .A(\ripple_adders[23].fa.sum ),
    .X(sum[23])
  );
  sky130_fd_sc_hd__buf_2 _311_ (
    .A(\ripple_adders[24].fa.sum ),
    .X(sum[24])
  );
  sky130_fd_sc_hd__buf_2 _312_ (
    .A(\ripple_adders[25].fa.sum ),
    .X(sum[25])
  );
  sky130_fd_sc_hd__buf_2 _313_ (
    .A(\ripple_adders[26].fa.sum ),
    .X(sum[26])
  );
  sky130_fd_sc_hd__buf_2 _314_ (
    .A(\ripple_adders[27].fa.sum ),
    .X(sum[27])
  );
  sky130_fd_sc_hd__buf_2 _315_ (
    .A(\ripple_adders[28].fa.sum ),
    .X(sum[28])
  );
  sky130_fd_sc_hd__buf_2 _316_ (
    .A(\ripple_adders[29].fa.sum ),
    .X(sum[29])
  );
  sky130_fd_sc_hd__buf_2 _317_ (
    .A(\ripple_adders[30].fa.sum ),
    .X(sum[30])
  );
  sky130_fd_sc_hd__buf_2 _318_ (
    .A(\ripple_adders[31].fa.sum ),
    .X(sum[31])
  );
endmodule
