/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module carry_bypass_synth(a, b, cin, sum, cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  wire \cba0.rca.ripple_adders[0].fa.sum ;
  wire \cba0.rca.ripple_adders[1].fa.sum ;
  wire \cba0.rca.ripple_adders[2].fa.sum ;
  wire \cba0.rca.ripple_adders[3].fa.sum ;
  wire \cba0.rca.ripple_adders[4].fa.sum ;
  wire \cba0.rca.ripple_adders[5].fa.sum ;
  wire \cba0.rca.ripple_adders[6].fa.sum ;
  wire \cba0.rca.ripple_adders[7].fa.sum ;
  wire \cba1.rca.ripple_adders[0].fa.sum ;
  wire \cba1.rca.ripple_adders[1].fa.sum ;
  wire \cba1.rca.ripple_adders[2].fa.sum ;
  wire \cba1.rca.ripple_adders[3].fa.sum ;
  wire \cba1.rca.ripple_adders[4].fa.sum ;
  wire \cba1.rca.ripple_adders[5].fa.sum ;
  wire \cba1.rca.ripple_adders[6].fa.sum ;
  wire \cba1.rca.ripple_adders[7].fa.sum ;
  wire \cba2.rca.ripple_adders[0].fa.sum ;
  wire \cba2.rca.ripple_adders[1].fa.sum ;
  wire \cba2.rca.ripple_adders[2].fa.sum ;
  wire \cba2.rca.ripple_adders[3].fa.sum ;
  wire \cba2.rca.ripple_adders[4].fa.sum ;
  wire \cba2.rca.ripple_adders[5].fa.sum ;
  wire \cba2.rca.ripple_adders[6].fa.sum ;
  wire \cba2.rca.ripple_adders[7].fa.sum ;
  wire \cba3.rca.ripple_adders[0].fa.sum ;
  wire \cba3.rca.ripple_adders[1].fa.sum ;
  wire \cba3.rca.ripple_adders[2].fa.sum ;
  wire \cba3.rca.ripple_adders[3].fa.sum ;
  wire \cba3.rca.ripple_adders[4].fa.sum ;
  wire \cba3.rca.ripple_adders[5].fa.sum ;
  wire \cba3.rca.ripple_adders[6].fa.sum ;
  wire \cba3.rca.ripple_adders[7].fa.sum ;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [31:0] sum;
  wire [31:0] sum;
  sky130_fd_sc_hd__and2_2 _128_ (
    .A(b[31]),
    .B(a[31]),
    .X(_127_)
  );
  sky130_fd_sc_hd__nor2_2 _129_ (
    .A(b[31]),
    .B(a[31]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_2 _130_ (
    .A(_127_),
    .B(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and2_2 _131_ (
    .A(b[30]),
    .B(a[30]),
    .X(_002_)
  );
  sky130_fd_sc_hd__nor2_2 _132_ (
    .A(b[30]),
    .B(a[30]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_2 _133_ (
    .A(_002_),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and2_2 _134_ (
    .A(b[29]),
    .B(a[29]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor2_2 _135_ (
    .A(b[29]),
    .B(a[29]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_2 _136_ (
    .A(_005_),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_2 _137_ (
    .A(b[28]),
    .B(a[28]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__or2_2 _138_ (
    .A(b[28]),
    .B(a[28]),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand2_2 _139_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_2 _140_ (
    .A(b[27]),
    .B(a[27]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__or2_2 _141_ (
    .A(b[27]),
    .B(a[27]),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_2 _142_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_2 _143_ (
    .A(b[26]),
    .B(a[26]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__or2_2 _144_ (
    .A(b[26]),
    .B(a[26]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2_2 _145_ (
    .A(_014_),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_2 _146_ (
    .A(b[25]),
    .B(a[25]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__or2_2 _147_ (
    .A(b[25]),
    .B(a[25]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_2 _148_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_2 _149_ (
    .A(b[24]),
    .B(a[24]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__or2_2 _150_ (
    .A(b[24]),
    .B(a[24]),
    .X(_021_)
  );
  sky130_fd_sc_hd__nand2_2 _151_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__and2_2 _152_ (
    .A(b[23]),
    .B(a[23]),
    .X(_023_)
  );
  sky130_fd_sc_hd__nor2_2 _153_ (
    .A(b[23]),
    .B(a[23]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_2 _154_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_2 _155_ (
    .A(b[22]),
    .B(a[22]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__or2_2 _156_ (
    .A(b[22]),
    .B(a[22]),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand2_2 _157_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_2 _158_ (
    .A(b[21]),
    .B(a[21]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__or2_2 _159_ (
    .A(b[21]),
    .B(a[21]),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand2_2 _160_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_2 _161_ (
    .A(b[20]),
    .B(a[20]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__or2_2 _162_ (
    .A(b[20]),
    .B(a[20]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_2 _163_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_2 _164_ (
    .A(b[19]),
    .B(a[19]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__or2_2 _165_ (
    .A(b[19]),
    .B(a[19]),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_2 _166_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_2 _167_ (
    .A(b[18]),
    .B(a[18]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__or2_2 _168_ (
    .A(b[18]),
    .B(a[18]),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2_2 _169_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_2 _170_ (
    .A(b[17]),
    .B(a[17]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__or2_2 _171_ (
    .A(b[17]),
    .B(a[17]),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand2_2 _172_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _173_ (
    .A(b[16]),
    .B(a[16]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__or2_2 _174_ (
    .A(b[16]),
    .B(a[16]),
    .X(_045_)
  );
  sky130_fd_sc_hd__nand2_2 _175_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__and2_2 _176_ (
    .A(b[15]),
    .B(a[15]),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2_2 _177_ (
    .A(b[15]),
    .B(a[15]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_2 _178_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_2 _179_ (
    .A(b[14]),
    .B(a[14]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__or2_2 _180_ (
    .A(b[14]),
    .B(a[14]),
    .X(_051_)
  );
  sky130_fd_sc_hd__nand2_2 _181_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_2 _182_ (
    .A(b[13]),
    .B(a[13]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__or2_2 _183_ (
    .A(b[13]),
    .B(a[13]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand2_2 _184_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_2 _185_ (
    .A(b[12]),
    .B(a[12]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__or2_2 _186_ (
    .A(b[12]),
    .B(a[12]),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand2_2 _187_ (
    .A(_056_),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_2 _188_ (
    .A(b[11]),
    .B(a[11]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__or2_2 _189_ (
    .A(b[11]),
    .B(a[11]),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2_2 _190_ (
    .A(_059_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_2 _191_ (
    .A(b[10]),
    .B(a[10]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or2_2 _192_ (
    .A(b[10]),
    .B(a[10]),
    .X(_063_)
  );
  sky130_fd_sc_hd__nand2_2 _193_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_2 _194_ (
    .A(b[9]),
    .B(a[9]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__or2_2 _195_ (
    .A(b[9]),
    .B(a[9]),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand2_2 _196_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_2 _197_ (
    .A(b[8]),
    .B(a[8]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__inv_2 _198_ (
    .A(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_2 _199_ (
    .A(b[8]),
    .B(a[8]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_2 _200_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_2 _201_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_2 _202_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_2 _203_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_2 _204_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_2 _205_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_2 _206_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_2 _207_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_2 _208_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__or2_2 _209_ (
    .A(b[0]),
    .B(a[0]),
    .X(_080_)
  );
  sky130_fd_sc_hd__nand2_2 _210_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a21bo_2 _211_ (
    .A1(cin),
    .A2(_080_),
    .B1_N(_079_),
    .X(_082_)
  );
  sky130_fd_sc_hd__or2_2 _212_ (
    .A(b[1]),
    .B(a[1]),
    .X(_083_)
  );
  sky130_fd_sc_hd__nand2_2 _213_ (
    .A(_078_),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a21bo_2 _214_ (
    .A1(_082_),
    .A2(_083_),
    .B1_N(_078_),
    .X(_085_)
  );
  sky130_fd_sc_hd__or2_2 _215_ (
    .A(b[2]),
    .B(a[2]),
    .X(_086_)
  );
  sky130_fd_sc_hd__nand2_2 _216_ (
    .A(_077_),
    .B(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a21bo_2 _217_ (
    .A1(_085_),
    .A2(_086_),
    .B1_N(_077_),
    .X(_088_)
  );
  sky130_fd_sc_hd__or2_2 _218_ (
    .A(b[3]),
    .B(a[3]),
    .X(_089_)
  );
  sky130_fd_sc_hd__nand2_2 _219_ (
    .A(_076_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21bo_2 _220_ (
    .A1(_088_),
    .A2(_089_),
    .B1_N(_076_),
    .X(_091_)
  );
  sky130_fd_sc_hd__or2_2 _221_ (
    .A(b[4]),
    .B(a[4]),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand2_2 _222_ (
    .A(_075_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a21bo_2 _223_ (
    .A1(_091_),
    .A2(_092_),
    .B1_N(_075_),
    .X(_094_)
  );
  sky130_fd_sc_hd__or2_2 _224_ (
    .A(b[5]),
    .B(a[5]),
    .X(_095_)
  );
  sky130_fd_sc_hd__nand2_2 _225_ (
    .A(_074_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21bo_2 _226_ (
    .A1(_094_),
    .A2(_095_),
    .B1_N(_074_),
    .X(_097_)
  );
  sky130_fd_sc_hd__or2_2 _227_ (
    .A(b[6]),
    .B(a[6]),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand2_2 _228_ (
    .A(_073_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a21bo_2 _229_ (
    .A1(_097_),
    .A2(_098_),
    .B1_N(_073_),
    .X(_100_)
  );
  sky130_fd_sc_hd__or2_2 _230_ (
    .A(b[7]),
    .B(a[7]),
    .X(_101_)
  );
  sky130_fd_sc_hd__nand2_2 _231_ (
    .A(_072_),
    .B(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21boi_2 _232_ (
    .A1(_100_),
    .A2(_101_),
    .B1_N(_072_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21ai_2 _233_ (
    .A1(_070_),
    .A2(_103_),
    .B1(_068_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21bo_2 _234_ (
    .A1(_066_),
    .A2(_104_),
    .B1_N(_065_),
    .X(_105_)
  );
  sky130_fd_sc_hd__a21bo_2 _235_ (
    .A1(_063_),
    .A2(_105_),
    .B1_N(_062_),
    .X(_106_)
  );
  sky130_fd_sc_hd__a21bo_2 _236_ (
    .A1(_060_),
    .A2(_106_),
    .B1_N(_059_),
    .X(_107_)
  );
  sky130_fd_sc_hd__a21bo_2 _237_ (
    .A1(_057_),
    .A2(_107_),
    .B1_N(_056_),
    .X(_108_)
  );
  sky130_fd_sc_hd__a21bo_2 _238_ (
    .A1(_054_),
    .A2(_108_),
    .B1_N(_053_),
    .X(_109_)
  );
  sky130_fd_sc_hd__a21bo_2 _239_ (
    .A1(_051_),
    .A2(_109_),
    .B1_N(_050_),
    .X(_110_)
  );
  sky130_fd_sc_hd__a21o_2 _240_ (
    .A1(_049_),
    .A2(_110_),
    .B1(_047_),
    .X(_111_)
  );
  sky130_fd_sc_hd__a21bo_2 _241_ (
    .A1(_045_),
    .A2(_111_),
    .B1_N(_044_),
    .X(_112_)
  );
  sky130_fd_sc_hd__a21bo_2 _242_ (
    .A1(_042_),
    .A2(_112_),
    .B1_N(_041_),
    .X(_113_)
  );
  sky130_fd_sc_hd__a21bo_2 _243_ (
    .A1(_039_),
    .A2(_113_),
    .B1_N(_038_),
    .X(_114_)
  );
  sky130_fd_sc_hd__a21bo_2 _244_ (
    .A1(_036_),
    .A2(_114_),
    .B1_N(_035_),
    .X(_115_)
  );
  sky130_fd_sc_hd__a21bo_2 _245_ (
    .A1(_033_),
    .A2(_115_),
    .B1_N(_032_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a21bo_2 _246_ (
    .A1(_030_),
    .A2(_116_),
    .B1_N(_029_),
    .X(_117_)
  );
  sky130_fd_sc_hd__a21bo_2 _247_ (
    .A1(_027_),
    .A2(_117_),
    .B1_N(_026_),
    .X(_118_)
  );
  sky130_fd_sc_hd__a21o_2 _248_ (
    .A1(_025_),
    .A2(_118_),
    .B1(_023_),
    .X(_119_)
  );
  sky130_fd_sc_hd__a21bo_2 _249_ (
    .A1(_021_),
    .A2(_119_),
    .B1_N(_020_),
    .X(_120_)
  );
  sky130_fd_sc_hd__a21bo_2 _250_ (
    .A1(_018_),
    .A2(_120_),
    .B1_N(_017_),
    .X(_121_)
  );
  sky130_fd_sc_hd__a21bo_2 _251_ (
    .A1(_015_),
    .A2(_121_),
    .B1_N(_014_),
    .X(_122_)
  );
  sky130_fd_sc_hd__a21bo_2 _252_ (
    .A1(_012_),
    .A2(_122_),
    .B1_N(_011_),
    .X(_123_)
  );
  sky130_fd_sc_hd__a21bo_2 _253_ (
    .A1(_009_),
    .A2(_123_),
    .B1_N(_008_),
    .X(_124_)
  );
  sky130_fd_sc_hd__a21o_2 _254_ (
    .A1(_007_),
    .A2(_124_),
    .B1(_005_),
    .X(_125_)
  );
  sky130_fd_sc_hd__a21o_2 _255_ (
    .A1(_004_),
    .A2(_125_),
    .B1(_002_),
    .X(_126_)
  );
  sky130_fd_sc_hd__a21o_2 _256_ (
    .A1(_001_),
    .A2(_126_),
    .B1(_127_),
    .X(cout)
  );
  sky130_fd_sc_hd__xnor2_2 _257_ (
    .A(cin),
    .B(_081_),
    .Y(\cba0.rca.ripple_adders[0].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _258_ (
    .A(_082_),
    .B(_084_),
    .Y(\cba0.rca.ripple_adders[1].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _259_ (
    .A(_085_),
    .B(_087_),
    .Y(\cba0.rca.ripple_adders[2].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _260_ (
    .A(_088_),
    .B(_090_),
    .Y(\cba0.rca.ripple_adders[3].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _261_ (
    .A(_091_),
    .B(_093_),
    .Y(\cba0.rca.ripple_adders[4].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _262_ (
    .A(_094_),
    .B(_096_),
    .Y(\cba0.rca.ripple_adders[5].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _263_ (
    .A(_097_),
    .B(_099_),
    .Y(\cba0.rca.ripple_adders[6].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _264_ (
    .A(_100_),
    .B(_102_),
    .Y(\cba0.rca.ripple_adders[7].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _265_ (
    .A(_071_),
    .B(_103_),
    .Y(\cba1.rca.ripple_adders[0].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _266_ (
    .A(_067_),
    .B(_104_),
    .Y(\cba1.rca.ripple_adders[1].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _267_ (
    .A(_064_),
    .B(_105_),
    .Y(\cba1.rca.ripple_adders[2].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _268_ (
    .A(_061_),
    .B(_106_),
    .Y(\cba1.rca.ripple_adders[3].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _269_ (
    .A(_058_),
    .B(_107_),
    .Y(\cba1.rca.ripple_adders[4].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _270_ (
    .A(_055_),
    .B(_108_),
    .Y(\cba1.rca.ripple_adders[5].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _271_ (
    .A(_052_),
    .B(_109_),
    .Y(\cba1.rca.ripple_adders[6].fa.sum )
  );
  sky130_fd_sc_hd__xor2_2 _272_ (
    .A(_049_),
    .B(_110_),
    .X(\cba1.rca.ripple_adders[7].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _273_ (
    .A(_046_),
    .B(_111_),
    .Y(\cba2.rca.ripple_adders[0].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _274_ (
    .A(_043_),
    .B(_112_),
    .Y(\cba2.rca.ripple_adders[1].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _275_ (
    .A(_040_),
    .B(_113_),
    .Y(\cba2.rca.ripple_adders[2].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _276_ (
    .A(_037_),
    .B(_114_),
    .Y(\cba2.rca.ripple_adders[3].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _277_ (
    .A(_034_),
    .B(_115_),
    .Y(\cba2.rca.ripple_adders[4].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _278_ (
    .A(_031_),
    .B(_116_),
    .Y(\cba2.rca.ripple_adders[5].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _279_ (
    .A(_028_),
    .B(_117_),
    .Y(\cba2.rca.ripple_adders[6].fa.sum )
  );
  sky130_fd_sc_hd__xor2_2 _280_ (
    .A(_025_),
    .B(_118_),
    .X(\cba2.rca.ripple_adders[7].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _281_ (
    .A(_022_),
    .B(_119_),
    .Y(\cba3.rca.ripple_adders[0].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _282_ (
    .A(_019_),
    .B(_120_),
    .Y(\cba3.rca.ripple_adders[1].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _283_ (
    .A(_016_),
    .B(_121_),
    .Y(\cba3.rca.ripple_adders[2].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _284_ (
    .A(_013_),
    .B(_122_),
    .Y(\cba3.rca.ripple_adders[3].fa.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _285_ (
    .A(_010_),
    .B(_123_),
    .Y(\cba3.rca.ripple_adders[4].fa.sum )
  );
  sky130_fd_sc_hd__xor2_2 _286_ (
    .A(_007_),
    .B(_124_),
    .X(\cba3.rca.ripple_adders[5].fa.sum )
  );
  sky130_fd_sc_hd__xor2_2 _287_ (
    .A(_004_),
    .B(_125_),
    .X(\cba3.rca.ripple_adders[6].fa.sum )
  );
  sky130_fd_sc_hd__xor2_2 _288_ (
    .A(_001_),
    .B(_126_),
    .X(\cba3.rca.ripple_adders[7].fa.sum )
  );
  sky130_fd_sc_hd__buf_2 _289_ (
    .A(\cba0.rca.ripple_adders[0].fa.sum ),
    .X(sum[0])
  );
  sky130_fd_sc_hd__buf_2 _290_ (
    .A(\cba0.rca.ripple_adders[1].fa.sum ),
    .X(sum[1])
  );
  sky130_fd_sc_hd__buf_2 _291_ (
    .A(\cba0.rca.ripple_adders[2].fa.sum ),
    .X(sum[2])
  );
  sky130_fd_sc_hd__buf_2 _292_ (
    .A(\cba0.rca.ripple_adders[3].fa.sum ),
    .X(sum[3])
  );
  sky130_fd_sc_hd__buf_2 _293_ (
    .A(\cba0.rca.ripple_adders[4].fa.sum ),
    .X(sum[4])
  );
  sky130_fd_sc_hd__buf_2 _294_ (
    .A(\cba0.rca.ripple_adders[5].fa.sum ),
    .X(sum[5])
  );
  sky130_fd_sc_hd__buf_2 _295_ (
    .A(\cba0.rca.ripple_adders[6].fa.sum ),
    .X(sum[6])
  );
  sky130_fd_sc_hd__buf_2 _296_ (
    .A(\cba0.rca.ripple_adders[7].fa.sum ),
    .X(sum[7])
  );
  sky130_fd_sc_hd__buf_2 _297_ (
    .A(\cba1.rca.ripple_adders[0].fa.sum ),
    .X(sum[8])
  );
  sky130_fd_sc_hd__buf_2 _298_ (
    .A(\cba1.rca.ripple_adders[1].fa.sum ),
    .X(sum[9])
  );
  sky130_fd_sc_hd__buf_2 _299_ (
    .A(\cba1.rca.ripple_adders[2].fa.sum ),
    .X(sum[10])
  );
  sky130_fd_sc_hd__buf_2 _300_ (
    .A(\cba1.rca.ripple_adders[3].fa.sum ),
    .X(sum[11])
  );
  sky130_fd_sc_hd__buf_2 _301_ (
    .A(\cba1.rca.ripple_adders[4].fa.sum ),
    .X(sum[12])
  );
  sky130_fd_sc_hd__buf_2 _302_ (
    .A(\cba1.rca.ripple_adders[5].fa.sum ),
    .X(sum[13])
  );
  sky130_fd_sc_hd__buf_2 _303_ (
    .A(\cba1.rca.ripple_adders[6].fa.sum ),
    .X(sum[14])
  );
  sky130_fd_sc_hd__buf_2 _304_ (
    .A(\cba1.rca.ripple_adders[7].fa.sum ),
    .X(sum[15])
  );
  sky130_fd_sc_hd__buf_2 _305_ (
    .A(\cba2.rca.ripple_adders[0].fa.sum ),
    .X(sum[16])
  );
  sky130_fd_sc_hd__buf_2 _306_ (
    .A(\cba2.rca.ripple_adders[1].fa.sum ),
    .X(sum[17])
  );
  sky130_fd_sc_hd__buf_2 _307_ (
    .A(\cba2.rca.ripple_adders[2].fa.sum ),
    .X(sum[18])
  );
  sky130_fd_sc_hd__buf_2 _308_ (
    .A(\cba2.rca.ripple_adders[3].fa.sum ),
    .X(sum[19])
  );
  sky130_fd_sc_hd__buf_2 _309_ (
    .A(\cba2.rca.ripple_adders[4].fa.sum ),
    .X(sum[20])
  );
  sky130_fd_sc_hd__buf_2 _310_ (
    .A(\cba2.rca.ripple_adders[5].fa.sum ),
    .X(sum[21])
  );
  sky130_fd_sc_hd__buf_2 _311_ (
    .A(\cba2.rca.ripple_adders[6].fa.sum ),
    .X(sum[22])
  );
  sky130_fd_sc_hd__buf_2 _312_ (
    .A(\cba2.rca.ripple_adders[7].fa.sum ),
    .X(sum[23])
  );
  sky130_fd_sc_hd__buf_2 _313_ (
    .A(\cba3.rca.ripple_adders[0].fa.sum ),
    .X(sum[24])
  );
  sky130_fd_sc_hd__buf_2 _314_ (
    .A(\cba3.rca.ripple_adders[1].fa.sum ),
    .X(sum[25])
  );
  sky130_fd_sc_hd__buf_2 _315_ (
    .A(\cba3.rca.ripple_adders[2].fa.sum ),
    .X(sum[26])
  );
  sky130_fd_sc_hd__buf_2 _316_ (
    .A(\cba3.rca.ripple_adders[3].fa.sum ),
    .X(sum[27])
  );
  sky130_fd_sc_hd__buf_2 _317_ (
    .A(\cba3.rca.ripple_adders[4].fa.sum ),
    .X(sum[28])
  );
  sky130_fd_sc_hd__buf_2 _318_ (
    .A(\cba3.rca.ripple_adders[5].fa.sum ),
    .X(sum[29])
  );
  sky130_fd_sc_hd__buf_2 _319_ (
    .A(\cba3.rca.ripple_adders[6].fa.sum ),
    .X(sum[30])
  );
  sky130_fd_sc_hd__buf_2 _320_ (
    .A(\cba3.rca.ripple_adders[7].fa.sum ),
    .X(sum[31])
  );
endmodule
